services:
  - type: web
    name: pds-tool
    env: python
    buildCommand: pip install -r requirements.txt && cd frontend && npm install && npm run build && cd ..
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: PDS_SECRET_KEY
        generateValue: true
      - key: PDS_JWT_SECRET_KEY
        generateValue: true
      - key: PDS_CORS_ORIGINS
        sync: false
      - key: PDS_SMTP_HOST
        value: smtp.qq.com
      - key: PDS_SMTP_PORT
        value: 587
      - key: PDS_SMTP_USER
        sync: false
      - key: PDS_SMTP_PASSWORD
        sync: false
      - key: PDS_SMTP_FROM
        sync: false
      - key: PDS_ALIYUN_ACCESS_KEY_ID
        sync: false
      - key: PDS_ALIYUN_ACCESS_KEY_SECRET
        sync: false